apiVersion: apisix.apache.org/v2beta3
kind: ApisixTls
metadata:
  name: aquaman-portal
  namespace: aquaman-daily
spec:
  hosts:
  - aquaman-portal-daily.hho-inc.com
  secret:
    name: hho-inc.com
    namespace: default