apiVersion: apisix.apache.org/v2beta3
kind: ApisixTls
metadata:
  name: resty-gateway
  namespace: aquaman-daily
spec:
  hosts:
  - daily-api.hho-inc.com
  secret:
    name: hho-inc.com
    namespace: default