apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: ch-analytics
  namespace: clickhouse-analytics
spec:
  http:
  - name: root
    match:
      hosts:
      - ch-analy.db.hho-inc.com
      paths:
      - /*
    backends:
    - serviceName: clickhouse-clickhouse
      servicePort: 8123
