apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs
  namespace: clickhouse-analytics
provisioner: clickhouse-nfs
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"