apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: devops
spec:
  ports:
  - name: service
    port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32017
  selector:
    app: mongodb
  type: NodePort