apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: cube-api
spec:
  http:
  - name: root
    match:
      hosts:
      - cubejs.hho-inc.com
      paths:
      - /*
    backends:
    - serviceName: cube-api
      servicePort: 4000