apiVersion: v1
kind: PersistentVolume
metadata:
  name: cube-worker-01
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/cube-worker-01
    server: nfs2.hho-inc.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cube-worker-02
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/cube-worker-02
    server: nfs2.hho-inc.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cube-worker-03
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/cube-worker-03
    server: nfs2.hho-inc.com