apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cube-api
  labels:
    name:  cube-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  cube-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name:  cube-api
    spec:
      containers:
      - image: cubejs/cube:latest
        name:  cube-api
        env:
        - name: CUBEJS_API_SECRET
          value: c3ef13e66abcf0297a746c5ce6620f59
        - name: CUBEJS_CUBESTORE_HOST
          value: cubestore-router
        - name: CUBEJS_DB_HOST
          value: clickhouse-clickhouse.clickhouse
        - name: CUBEJS_DB_PORT
          value: "8123"
        - name: CUBEJS_DB_USER
          value: clickhouse_operator
        - name: CUBEJS_DB_PASS
          value: clickhouse_operator_password
        - name: CUBEJS_DB_TYPE
          value: clickhouse
        - name: CUBEJS_EXTERNAL_DEFAULT
          value: "true"
        - name: CUBEJS_SCHEDULED_REFRESH_DEFAULT
          value: "true"
        - name: CUBEJS_DEV_MODE
          value: "false"
        - name: CUBEJS_REDIS_URL
          value: redis://redis:6379
        ports:
        - containerPort: 3000
        - containerPort: 4000
        volumeMounts:
        - mountPath: /cube/conf/schema
          name: data
      volumes:
        - name: data
          nfs:
            path: /data/cube
            server: nfs.hho-inc.com