apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "clickhouse"
  namespace: clickhouse-logs

spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      logVolumeClaimTemplate: default
      podTemplate: clickhouse
      serviceTemplate: clickhouse-service

  configuration:
    zookeeper:
      nodes:
      - host: zk-cs
    clusters:
      - name: hho-logs
        layout:
          shardsCount: 4
          replicasCount: 1
    files:
      config.d/dictionaries.xml: |
        <clickhouse><dictionaries_config>dictionaries/*.xml</dictionaries_config></clickhouse>

  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          storageClassName: sc-nfs
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi

    serviceTemplates:
      - name: clickhouse-service
        spec:
          ports:
          - name: http
            port: 8123
          - name: tcp
            port: 9000
          type: NodePort

    podTemplates:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - {key: app.kubernetes.io/instance, operator: In, values: ['clickhouse-logs']}
              topologyKey: kubernetes.io/hostname
      containers:
      - name: clickhouse
        spec:
          containers:
            - name: clickhouse-pod
              image: reg.hho-inc.com/devops/clickhouse-server-maxmind:latest
              imagePullPolicy: Always