apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alertmanager
  name: alertmanager
  namespace: monitor
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
       app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: reg.hho-inc.com/devops/alertmanager:latest
        imagePullPolicy: IfNotPresent
        args:
        - --storage.path=/data
        - --config.file=/etc/config/alertmanager.yml
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 9093
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data
          name: storage-volume
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: alertmanager
      - name: storage-volume
        persistentVolumeClaim:
          claimName: alertmanager-data