apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitor
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname"]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: "web.hook"
    receivers:
    - name: "web.hook"
      webhook_configs:
        - url: "http://oops-api-serv.devops-daily:9001/apis/webhook/dingding?token=09e4073466c6f1df049ac87f1307e5dc88d71189940ae5311df814e722225566&template=basic_alarm"
          send_resolved: true

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['instance', 'job']