apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/alertmanager
    server: nfs.hho-inc.com