apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
  name: alertmanager
  namespace: monitor
spec:
  ports:
  - name: http
    port: 9093
    targetPort: 9093
  selector:
    app: alertmanager