apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
  namespace: monitor
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
       app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: reg.hho-inc.com/devops/blackbox-exporter:latest
        imagePullPolicy: IfNotPresent
        args:
        - --config.file=/etc/config/blackbox.yml
        ports:
        - containerPort: 9115
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: blockbox