apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox
  namespace: monitor
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          preferred_ip_protocol: "ip4"
          no_follow_redirects: true
          method: GET
      http_2xx_post:
        prober: http
        timeout: 10s
        http:
          method: POST
      tcp_connect:
        prober: tcp
      icmp_connect:
        prober: icmp
        timeout: 10s
        icmp:
          preferred_ip_protocol: "ip4"
      dns_ch.vcn.hho-inc.com_check:
        prober: dns
        dns: 
          preferred_ip_protocol: "ip4"
          query_name: "ch.vcn.hho-inc.com"