apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: blackbox-exporter
  namespace: monitor
spec:
  http:
  - name: root
    match:
      hosts:
      - blackbox.hho-inc.com
      paths:
      - /*
    backends:
    - serviceName: blackbox-exporter
      servicePort: 9115