apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitor
data:
  grafana.ini: |
    [server]
    protocol = http
    http_addr = 0.0.0.0
    http_port = 3000
    root_url = http://grafana.hho-inc.com
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus:9090