apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma
  namespace: monitor
  labels:
    app: kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuma
  template:
    metadata:
      labels:
        app: kuma
    spec:
      containers:
        - name: kuma
          image: louislam/uptime-kuma:1
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 3001
              name: service
          volumeMounts:
            - name: storage
              mountPath: /app/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: kuma-data
