apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data
  namespace: monitor
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce