apiVersion: v1
kind: PersistentVolume
metadata:
  name: kuma-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/kuma-data
    server: nfs.hho-inc.com