apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuma
  name: kuma
  namespace: monitor
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: kuma