apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitor
data:
  node_health.yml: |
    groups:
    - name: node_health
      rules:
      - alert: Node is down
        expr: up != 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: node is down
    
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 15s
      scrape_timeout: 10s
    rule_files:
      - /etc/config/node_health.yml
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

    - job_name: clickhouse
      static_configs:
      - targets:
        - clickhouse-operator-metrics.kube-system:8888

    - job_name: node-exporter
      consul_sd_configs:
      - server: consul-service.devops:8500
        services: ['node-exporter']

    - job_name: HTTPCheck
      scrape_configs: 15s
      metrics_path: /
      params: 
        module: [http_2xx_get]
      static_configs:
      - targets: ['https://ch.hhodata.com']
        labels:
          blackbox: 'HTTPCheck'
        
    - job_name: kubernetes-apiservers
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: default;kubernetes;https
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true