apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: skywalking
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - name: restful
    port: 9200
    targetPort: 9200
    nodePort: 31201
  - name: transport
    port: 9300
    targetPort: 9300
    nodePort: 31301
---
apiVersion: v1
kind: Service
metadata:
  name: es-cluster
  namespace: skywalking
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: restful
    port: 9200
  - name: transport
    port: 9300
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: skywalking
spec:
  serviceName: es-cluster
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
   metadata:
     labels:
       app: elasticsearch
   spec:
     securityContext:
       fsGroup: 1000
     affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - elasticsearch
           topologyKey: kubernetes.io/hostname
       nodeAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
         - weight: 80
           preference:
            matchExpressions:
            - key: instance
              operator: In
              values: ["clickhouse"]
     initContainers:
     - name: init
       image: busybox
       imagePullPolicy: IfNotPresent
       command: ["/bin/sh", "-c", "sysctl -w vm.max_map_count=262144; ulimit -n 65536; ulimit -u 2048; ulimit -l unlimited"]
       securityContext:
         privileged: true
     containers:
     - name: elasticsearch
       image: reg.hho-inc.com/devops/elasticsearch:7.10.1
       imagePullPolicy: Always
       resources:
         limits:
           cpu: 2
           memory: 4G
         requests:
           cpu: 1
           memory: 1G
       ports:
       - containerPort: 9200
         name: restful
       - containerPort: 9300
         name: transport
       env:
       - name: cluster.name
         valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
       - name: node.name
         valueFrom:
           fieldRef:
             fieldPath: metadata.name
       - name: POD_IP
         valueFrom:
           fieldRef:
             fieldPath: status.podIP
       - name: discovery.seed_hosts
         value: "es-0.es-cluster,es-1.es-cluster,es-2.es-cluster"
       - name: cluster.initial_master_nodes
         value: "es-0,es-1,es-2"
       - name: ES_JAVA_OPTS
         value: "-Xms1024m -Xmx1024m"
       volumeMounts:
       - name: es-data
         mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: sc-nfs-skywalking
      resources:
        requests:
          storage: 500Gi
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: es
  namespace: skywalking
spec:
  http:
  - name: root
    match:
      hosts:
      - es-skywalking.hho-inc.com
      paths:
      - /*
    backends:
    - serviceName: es
      servicePort: 9200