apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap
  namespace: skywalking
  labels:
    app: skywalking
    component: "oap"
spec:
  type: ClusterIP
  ports:
  - port: 11800
    name: grpc
  - port: 12800
    name: rest
  selector:
    app: skywalking
    component: "oap"
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-satellite
  namespace: skywalking
  labels:
    app: skywalking
    component: "satellite"
spec:
  type: ClusterIP
  ports:
  - port: 11800
    name: grpc
  - port: 1234
    name: prometheus
  selector:
    app: skywalking
    component: "satellite"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking
    component: "ui"
  name: skywalking-ui
  namespace: skywalking
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

  selector:
    app: skywalking
    component: "ui"