apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs-skywalking
  namespace: clickhouse-skywalking
provisioner: clickhouse-nfs-skywalking
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"