apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-ui
  labels:
    app: skywalking
    component: "ui"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking
      component: "ui"
  template:
    metadata:
      labels:
        app: skywalking
        component: "ui"
    spec:
      containers:
      - name: ui
        image: skywalking.docker.scarf.sh/apache/skywalking-ui:8.8.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: page
        env:
        - name: SW_OAP_ADDRESS
          value: http://skywalking-oap:12800
        - name: TZ
          value: Asia/Shanghai