apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resty-gateway
  name: resty-gateway
  namespace: aquaman-daily
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
       app: resty-gateway
  template:
    metadata:
      labels:
        app: resty-gateway
    spec:
      containers:
      - name: resty-gateway
        image: reg.hho-inc.com/aquaman-daily/resty-gateway:1654498299
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name:  config-volume
            mountPath:  /usr/local/openresty/nginx/conf
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: resty-gateway

---
kind: Service
apiVersion: v1
metadata:
  name:  resty-gateway-serv
  namespace: aquaman-daily
spec:
  selector:
    app: resty-gateway
  ports:
  - name:  gateway
    port:  80
    targetPort:  80

---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: resty-gateway
  namespace: aquaman-daily
spec:
  http:
  - name: root
    match:
      hosts:
      - daily-api.hho-inc.com
      paths:
      - /*
    plugins:
    - name: redirect
      enable: true
      config:
        http_to_https: true
    backends:
    - serviceName: resty-gateway-serv
      servicePort: 80

---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixTls
metadata:
  name: resty-gateway
  namespace: aquaman-daily
spec:
  hosts:
  - daily-api.hho-inc.com
  secret:
    name: daily-api
    namespace: aquaman-daily