apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resty-gateway
  name: resty-gateway
  namespace: aquaman-daily
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
       app: resty-gateway
  template:
    metadata:
      labels:
        app: resty-gateway
    spec:
      containers:
      - name: resty-gateway
        image: reg.hho-inc.com/aquaman-daily/resty-gateway:1654482411
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name:  resty-gateway-serv
  namespace: aquaman-daily
spec:
  selector:
    app: resty-gateway
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  80

---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: resty-gateway
  namespace: aquaman-daily
spec:
  http:
  - name: root
    match:
      hosts:
      - daiy-api.hho-inc.com
      paths:
      - /*
    backends:
    - serviceName: resty-gateway-serv
      servicePort: 80